spring:
    profiles: dev
    datasource:
        master:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbcUrl: jdbc:mysql://${DB_IP:ubuntu2004.wsl}:${DB_PORT:3306}/${DB_NAME:neobradley-simple}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
            username: ${DB_USER:root}
            password: ${DB_PASS:neobradleypass}
server:
    port: 8080
swagger:
    enabled: true
logging:
    level:
        root: info
    file:
        path: /var/log/app
