name: docker
on:
  push:
    tags: [ "*.*.*" ]

env:
  REGISTRY: docker.pkg.github.com
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - run: chmod +x gradlew
        working-directory: ./simple-service

      - run: ./gradlew -Penv=uat docker
        working-directory: ./simple-service

      - id: meta-service
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/service
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true

      - id: meta-web
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/web
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true

      - id: meta-db
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/db
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.APP_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./simple-service/build/application/docker
          tags: ${{ steps.meta-service.outputs.tags }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          context: ./simple-web
          tags: ${{ steps.meta-web.outputs.tags }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          context: ./sql
          tags: ${{ steps.meta-db.outputs.tags }}
          push: true